### ISSUE TITLE
Improve REPL latency

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/MKL.jl#1]
Currently, the new system image doesn't include the precompile information in `generate_precompile.jl`. Once https://github.com/JuliaLang/julia/pull/30367 is included in a Julia release, it should be possible to fix this issue and therefore match the latency of the official binaries.

**Comment by PallHaraldsson** [comment]
@Jutho
> Is there a manual fix for this issue if you have built Julia from source?

I suppose. JuliaPro had MKL at some point. I'm not sure how it was integrated, but you would have to compile Julia without GPL, and probably do more to fix the latency. As the README says, this can be fixed with Julia 1.1 (now out). I'm not sure how 1.1 fits into this, but at least a Julia (was it 0.6 version?) distro with MKL was possible (and still is available; just not recommended).

**Comment by Jutho** [comment]
Would it be just a matter of rerunning the `generate_precompile.jl` script? I have not tried and am not very familiar with everything related to the sysimg of julia.

**Comment by KristofferC** [comment]
Yes, it is just a matter of running that script during creation of the sysimage.

**Comment by Jutho** [comment]
My apologies but just to make sure that I understand correctly, in some more detail:
* Install Julia (only from source, or also with binary, e.g. 1.1 ?)
* Start Julia, run `import Pkg; Pkg.add("MKL")`
* Find "generate_precompile.jl" and do `include("generate_precompile.jl") in running Julia session?

I will give it a try asap.

**Comment by KristofferC** [comment]
No, that is not correct. The `include("generate_precompile.jl")` needs to happen *during* the generation of the sysimg so somewhere in the call to `PackageCompiler`.

**Comment by andreasnoack** [comment]
We can't do this for binary distributions yet since `generate_precompile.jl` isn't included, see https://github.com/JuliaLang/julia/pull/30367. I guess we should really just merge that PR.

**Comment by Jutho** [comment]
> so somewhere in the call to PackageCompiler.

I am still confused after reading https://github.com/JuliaLang/julia/pull/30367: Is it at this point clear what exactly needs to happen, and is it just a matter of e.g. bundling the "generate_precompile.jl" script with the binary? Can't it just be downloaded from github when the package is build? Anyway, if so, is it possible to provide a clear set of instructions what exactly needs to be done  ("change this line to that, add that line") by non-expert people (i.e. me) that want to try this out with a julia distro built from source?

Or is it still unclear exactly what to do?

**Comment by andreasnoack** [comment]
We could just download it but I'd prefer not to. Even if it was available, I'd have to figure out the correct invocation of PackageCompiler since the function I'm currently using doesn't allow me to add a file when generating the system image. It shouldn't be hard, though.

**Comment by KristofferC** [comment]
Can use `PackageCompiler.build_sysimg(PackageCompiler.default_sysimg_path(), "generate_precompile.jl")`

**Comment by tpapp** [comment]
The README says that REPL latency would be fixed with Julia 1.1, is it still an issue?

**Comment by andreasnoack** [comment]
Unfortunately, it is.

**Comment by aminya** [comment]
Is this issue abandoned?

**Comment by Jutho** [comment]
I've had no problems with the final suggestion, i.e. install MKL.jl and PackageCompiler.jl, and after building MKL, just run
```julia
import PackageCompiler
PackageCompiler.build_sysimg(PackageCompiler.default_sysimg_path(), "generate_precompile.jl")
```
You only need to make sure to have the file "generate_precompile.jl" (and execute this command in the directory where the file is located). If you build Julia from source, its in `julia/contrib/`, otherwise you can still download it from Github (preferably the version that matches the version of Julia you have installed, which you can obtain by browsing the source code for the release version).

**Comment by daviehh** [comment]
I tried @KristofferC 's suggestion to use `PackageCompiler.build_sysimg(PackageCompiler.default_sysimg_path(), "generate_precompile.jl")` for the generation of a new sys img during the install process, by downloading the "generate_precompile.jl" file: https://github.com/daviehh/MKL.jl/commit/88aa8326cb45807c5dc7f037510002c3c6e54808

but it fails on julia 1.0:
https://travis-ci.com/daviehh/MKL.jl/builds/137627397#L468
with "AssertionError: n_succeeded > 3500"

testing on julia 1.2 https://github.com/daviehh/MKL.jl/commit/28faa48ebac1ace32a975c05252a4c2331074679

it fails due to missing repl?
https://travis-ci.com/daviehh/MKL.jl/builds/137627432#L493

**Comment by KristofferC** [comment]
Try comment out that assertion.

**Comment by aminya** [comment]
I think we can finally close this issue 🚀 .
