### ISSUE TITLE
Renaming BLAS name only locally?

### ISSUE THREAD

**Issue by volkerkarle** [JuliaComputing/MKL.jl#31]
Dear folks,

I am working on a cluster and I cannot open/rename the  libblas_name since it is not locally available:

┌ Error: *Error building `MKL`:
*│ *[ Info: Replacing libblas_name in
.../shared/julia/1.3.1/bin/../share/julia/base/build_h.jl
*│ *ERROR: LoadError: SystemError: opening file
.../shared/julia/1.3.1/bin/../share/julia/base/build_h.jl":
Permission denied

How can I install MKL nevertheless?

Best,
V.

**Comment by KristofferC** [comment]
The way this package works is by overwriting some of the files in the julia installation and then "recompiling" a part of Julia with those modified files. You would need to have write permissions to the Julia installation. You can usually just download Julia from https://julialang.org/downloads/ and use that instead of using the shared installation.
